language: cpp
branches:
  only:
  - master
  - /^v.*$/
matrix:
  fast_finish: true
  include:
  - os: linux
    env: PYTHON=3.6
 
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - libblas-dev
    - liblapack-dev
    - gfortran
    - cmake
    - python3-dev
    - libboost-all-dev
    - libgsl0-dev
    - libeigen3-dev

before_install:
- |
  pyenv shell 3.6.3
- |
  PIP=pip
  PY=python$PYTHON
  which $PY
  which pip
  $PY -V 
  ls -hl /opt/pyenv/shims
  python3 -V
- |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then 
    export CXX=g++-4.9 CC=gcc-4.9; 
    pip install --user --upgrade pip virtualenv    
  fi

- |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then 
    virtualenv -p $PY venv
    source venv/bin/activate
  fi

install:
- |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    cmake similarity_search -DWITH_EXTRAS=1
  else
    cmake similarity_search
  fi
  make -j 4
  travis_wait travis_retry $PIP install -r python_bindings/requirements.txt scipy six flake8 wheel
  travis_retry cd python_bindings && $PY setup.py build install && cd ..
  ls -lh
  cd python_bindings && $PY -W ignore setup.py bdist_wheel && ls -lh && ls -hlR dist/*  

script:
- $PY --version
- pwd
- ls -hl dist
- ls -hl ..

deploy:
  provider: releases
  api_key: "${GITHUB_OAUTH_TOKEN}"
  file: "python_bindings/dist/nmslib-1.7.3.4-cp36-cp36m-linux_x86_64.whl"
  skip_cleanup: true
  on:
    repo: timedcy/nmslib
    tags: false
    all_branches: true
    
cache:
  - apt
  - directories:
    - $HOME/.cache/pip

