language: cpp

matrix:
  fast_finish: true
  include:
  - os: linux
    env: PYTHON=3.6
 
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - libblas-dev
    - liblapack-dev
    - gfortran
    - cmake
    - python3-dev
    - libboost-all-dev
    - libgsl0-dev
    - libeigen3-dev

before_install:
- |
  which python$PYTHON
  python$PYTHON -V
  PIP=pip
  PY=python
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then 
    export CXX=g++-4.8 CC=gcc-4.8; 
    pip install --user --upgrade pip virtualenv
    #virtualenv -p python$PYTHON venv_py3.6
    #source venv_py3.6/bin/activate
  fi

install:
- |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    cmake similarity_search -DWITH_EXTRAS=1
  else
    cmake similarity_search
  fi
  make -j 4
  travis_wait travis_retry $PIP install -r python_bindings/requirements.txt scipy six flake8
  travis_retry cd python_bindings && $PY setup.py build install && cd ..

script:
- $PY --version
- cd python_bindings && $PY setup.py test && cd ..
- |
  set -e
  if [ "$TRAVIS_OS_NAME" = "linux" ] ; then
      cd similarity_search;
      ./release/bunit
      ./release/test_integr integr.log 
      cd ..
      ls -lh
  fi

cache:
  - apt
  - directories:
    - $HOME/.cache/pip

