language: cpp

sudo: required

addons:
  apt:
    packages: &core_build
    - g++-4.9
    - libblas-dev
    - liblapack-dev
    - gfortran
    - cmake
    - libboost-all-dev
    - libgsl0-dev
    - libeigen3-dev
  homebrew:
    packages:
    - pyenv
    update: true

matrix:
  fast_finish: true
  include:
  - os: linux
    dist: trusty
    env: PYTHON=2.7
    services:
    - docker
    addons:
      apt:
        update: true
        sources:
        - ubuntu-toolchain-r-test
        - deadsnakes
        packages:
          - *core_build
          - python2.7-dev
  - os: linux
    env: PYTHON=3.5
    dist: trusty
    services:
    - docker
    addons:
      apt:
        update: true
        sources:
        - ubuntu-toolchain-r-test
        - deadsnakes
        packages:
        - *core_build
        - python3.5-dev
  - os: linux
    env: PYTHON=3.6
    dist: xenial
    services:
    - docker
    addons:
      apt:
        update: true
        sources:
        - ubuntu-toolchain-r-test
        - deadsnakes
        packages:
        - *core_build
        - python3.6-dev
  - os: linux
    env: PYTHON=3.7
    dist: xenial
    services:
    - docker
    addons:
      apt:
        update: true
        sources:
        - ubuntu-toolchain-r-test
        - deadsnakes
        packages:
        - *core_build
        - python3.7-dev
  - os: osx
    env: PYTHON=2.7-dev
    osx_image: xcode9.2
  - os: osx
    env: PYTHON=3.5-dev
    osx_image: xcode9.2
  - os: osx
    env: PYTHON=3.6-dev
    osx_image: xcode9.2
  - os: osx
    env: PYTHON=3.7-dev
    osx_image: xcode9.2
  - os: osx
    env: PYTHON=2.7-dev
    osx_image: xcode9.4
  - os: osx
    env: PYTHON=3.5-dev
    osx_image: xcode9.4
  - os: osx
    env: PYTHON=3.6-dev
    osx_image: xcode9.4
  - os: osx
    env: PYTHON=3.7-dev
    osx_image: xcode9.4
  - os: osx
    env: PYTHON=2.7-dev
    osx_image: xcode11.2
  - os: osx
    env: PYTHON=3.5-dev
    osx_image: xcode11.2
  - os: osx
    env: PYTHON=3.6-dev
    osx_image: xcode11.2
  - os: osx
    env: PYTHON=3.7-dev
    osx_image: xcode11.2
  allow_failures:
  - os: osx

before_install:
- |
  PIP="python -m pip"
  PY=python
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then 
    export CXX=g++-4.9 CC=gcc-4.9;
  fi

  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    pyenv install $PYTHON
    PY=/Users/travis/.pyenv/versions/${PYTHON}/bin/python
    PIP="$PY -m pip"
  fi
  sudo -H $PIP install --upgrade pip

install:
- |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    cmake similarity_search -DWITH_EXTRAS=1
  else
    cmake similarity_search
  fi
  make -j 4
  $PIP install --user scipy six flake8 psutil
  cd python_bindings
  $PIP install --user -r requirements.txt
  $PY setup.py build_ext
  $PIP install --user .
  cd ..

script:
- $PY --version
- cd python_bindings && $PY setup.py test && cd ..
- |
  set -e
  if [ "$TRAVIS_OS_NAME" = "linux" ] ; then
      cd similarity_search;
      ./release/bunit
      ./release/test_integr integr.log 
      cd ..
  fi

after_script:
  - |
    if [ "$TRAVIS_TAG" ]; then
      git clean -fxd
      git clean -fXd
      mv .pypirc ~/.pypirc
      $PIP install --user twine
      if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        # manylinux build
        echo "Building manylinux wheels with auditwheel and docker"
        for PLAT in manylinux1_x86_64 manylinux1_i686 manylinux2010_x86_64; do
          DOCKER_IMAGE=quay.io/pypa/$PLAT
          if [ "$PLAT" == "manylinux1_i686" ]; then
            PRE_CMD=linux32
          else
            PRE_CMD=""
          fi
          docker pull $DOCKER_IMAGE
          docker run --rm -v `pwd`:/io -e PLAT=$PLAT -e PYTHON=$PYTHON $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
        done
        WHEEL_DIR="wheelhouse"
      else
        # os x build
        echo "Building Mac OS wheels natively"
        set -x
        cd python_bindings
        $PIP install --user -r dev-requirements.txt
        $PY setup.py build_ext
        $PY setup.py sdist bdist_wheel
        WHEEL_DIR="dist"
        cd ..
      fi
      cd python_bindings
      $PY -m twine upload -r pypi -p $PYPI_PASSWORD --skip-existing ${WHEEL_DIR}/*
    else
      echo "Skipping deployment because this is not a tagged commit"
    fi

before_cache:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew cleanup; fi

cache:
  - apt
  - directories:
    - $HOME/.cache/pip
    - $HOME/Library/Caches/Homebrew

